# To Create the environment, run conda env create -f environment.yml
name: iris-app-env
dependencies:
- appnope=0.1.0=py35_0
- click=6.6=py35_0
- decorator=4.0.10=py35_0
- flask=0.11.1=py35_0
- flask-wtf=0.12=py35_0
- gunicorn=19.1.0=py35_0
- ipython=5.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- mkl=11.3.3=0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- pastedeploy=1.5.2=py35_1
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.3=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.6.1=py35_0
- readline=6.2=2
- scikit-learn=0.17.1=np111py35_2
- scipy=0.18.0=np111py35_0
- setuptools=25.1.6=py35_0
- simplegeneric=0.8.1=py35_1
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.2=py35_0
- wcwidth=0.1.7=py35_0
- werkzeug=0.11.10=py35_0
- wheel=0.29.0=py35_0
- wtforms=2.1=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - prompt-toolkit==1.0.3

